module.exports = {
    extends: [
      'stylelint-config-standard',
      'stylelint-config-property-sort-order-smacss'
    ],
    defaultSeverity: 'warning',
    rules: {
      indentation: 2,
      'selector-max-compound-selectors': 7,
      'max-nesting-depth': [7, {
        ignore: ['blockless-at-rules']
      }],
  
      'color-hex-case': 'lower',
      'color-hex-length': 'short',
      'color-named': 'never',
      'color-no-hex': null,
      'color-no-invalid-hex': true,
      'selector-type-no-unknown': null,
  
      'function-blacklist': [
        'hsv',
        'hsva',
        'hue',
        'saturation',
        'lightness',
        'hsvhue',
        'hsvsaturation',
        'hsvvalue',
        'red',
        'green',
        'blue',
        'alpha',
        'luma',
        'luminance',
        'desaturate',
        'lighten',
        'darken',
        'fadein',
        'fadeout',
        'spin',
        'mix',
        'argb',
        'color',
        'tint',
        'shade',
        'multiply',
        'screen',
        'overlay',
        'softlight',
        'hardlight',
        'difference',
        'exclusion',
        'average',
        'negation',
        'e',
        'escape',
        'replace',
        '%',
        'min',
        'max',
        'convert',
        'pi',
        'mod',
        'pow',
        'percentage',
        'ceil',
        'floor',
        'round',
        'sqrt',
        'abs',
        'tan',
        'sin',
        'cos',
        'atan',
        'asin',
        'acos',
        'isruleset',
        'iscolor',
        'isnumber',
        'isstring',
        'iskeyword',
        'isurl',
        'ispixel',
        'ispercentage',
        'isem',
        'isunit',
        'extract',
        'length',
        'svg-gradient',
        'data-uri'
      ]
    }
  };